apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus
    app.kubernetes.io/part-of: load-app-406684b3-fdfa-4cba-b272-c78d553a9d54
  name: devfile-sample-code-with-quarkus
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-41-tenant/load-app-406684b3-fdfa-4cba-b272-c78d553a9d54/devfile-sample-code-with-quarkus@sha256:075253d497066825b51c65cc32c3968bbf6760def3ed538cd59ee27ba85a278b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
